In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("surendra365/recruitement-dataset")

print("Path to dataset files:", path)

/Users/suhoon/Desktop/Personal_Find_Job_Helper/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading from https://www.kaggle.com/api/v1/datasets/download/surendra365/recruitement-dataset?dataset_version_number=2...

100%|██████████| 1.58M/1.58M [00:00<00:00, 2.31MB/s]

Extracting files...
Path to dataset files: /Users/suhoon/.cache/kagglehub/datasets/surendra365/recruitement-dataset/versions/2

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('job_applicant_dataset.csv')

In [4]:
df

,Job Applicant Name,Age,Gender,Race,Ethnicity,Resume,Job Roles,Job Description,Best Match
0,Daisuke Mori,29,Male,Mongoloid/Asian,Vietnamese,"Proficient in Injury Prevention, Motivation, N...",Fitness Coach,A Fitness Coach is responsible for helping cl...,0
1,Taichi Shimizu,31,Male,Mongoloid/Asian,Filipino,"Proficient in Healthcare, Pharmacology, Medica...",Physician,"Diagnose and treat illnesses, prescribe medica...",0
2,Sarah Martin,46,Female,White/Caucasian,Dutch,"Proficient in Forecasting, Financial Modelling...",Financial Analyst,"As a Financial Analyst, you will be responsibl...",0
3,Keith Hughes,43,Male,Negroid/Black,Caribbean,"Proficient in Budgeting, Supply Chain Optimiza...",Supply Chain Manager,A Supply Chain Manager oversees the entire sup...,1
4,James Davis,49,Male,White/Caucasian,English,"Proficient in Logistics, Negotiation, Procurem...",Supply Chain Manager,A Supply Chain Manager oversees the entire sup...,1
...,...,...,...,...,...,...,...,...,...
9995,Jada Williams,30,Female,Negroid/Black,Ghanaian,"Proficient in Biology, Regulatory Compliance, ...",Biomedical Engineer,A Biomedical Engineer designs and develops med...,0
9996,Jaden Carter,52,Male,Negroid/Black,Nigerian,"Proficient in Communication, Teamwork, Lesson ...",Teacher,A Teacher shapes the future of students by del...,0
9997,Mia Foster,25,Female,White/Caucasian,German,"Proficient in Medical Terminology, Critical Th...",Physician,"Diagnose and treat illnesses, prescribe medica...",0
9998,Stella Green,51,Female,White/Caucasian,Irish,"Proficient in Exercise Programming, Motivation...",Fitness Coach,A Fitness Coach is responsible for helping cl...,1
9999,Ryo Nishida,46,Male,Mongoloid/Asian,Thai,"Proficient in Content Strategy, Copywriting, C...",Content Writer,"As a Content Writer, you will create written m...",0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Job Applicant Name  10000 non-null  object
 1   Age                 10000 non-null  int64
 2   Gender              10000 non-null  object
 3   Race                10000 non-null  object
 4   Ethnicity           10000 non-null  object
 5   Resume              10000 non-null  object
 6   Job Roles           10000 non-null  object
 7   Job Description     10000 non-null  object
 8   Best Match          10000 non-null  int64
dtypes: int64(2), object(7)
memory usage: 703.3+ KB

In [20]:
df.drop(columns=['Job Applicant Name'])

,Age,Gender,Race,Ethnicity,Resume,Job Roles,Job Description,Best Match
0,29,Male,Mongoloid/Asian,Vietnamese,"Proficient in Injury Prevention, Motivation, N...",Fitness Coach,A Fitness Coach is responsible for helping cl...,0
1,31,Male,Mongoloid/Asian,Filipino,"Proficient in Healthcare, Pharmacology, Medica...",Physician,"Diagnose and treat illnesses, prescribe medica...",0
2,46,Female,White/Caucasian,Dutch,"Proficient in Forecasting, Financial Modelling...",Financial Analyst,"As a Financial Analyst, you will be responsibl...",0
3,43,Male,Negroid/Black,Caribbean,"Proficient in Budgeting, Supply Chain Optimiza...",Supply Chain Manager,A Supply Chain Manager oversees the entire sup...,1
4,49,Male,White/Caucasian,English,"Proficient in Logistics, Negotiation, Procurem...",Supply Chain Manager,A Supply Chain Manager oversees the entire sup...,1
...,...,...,...,...,...,...,...,...
9995,30,Female,Negroid/Black,Ghanaian,"Proficient in Biology, Regulatory Compliance, ...",Biomedical Engineer,A Biomedical Engineer designs and develops med...,0
9996,52,Male,Negroid/Black,Nigerian,"Proficient in Communication, Teamwork, Lesson ...",Teacher,A Teacher shapes the future of students by del...,0
9997,25,Female,White/Caucasian,German,"Proficient in Medical Terminology, Critical Th...",Physician,"Diagnose and treat illnesses, prescribe medica...",0
9998,51,Female,White/Caucasian,Irish,"Proficient in Exercise Programming, Motivation...",Fitness Coach,A Fitness Coach is responsible for helping cl...,1
9999,46,Male,Mongoloid/Asian,Thai,"Proficient in Content Strategy, Copywriting, C...",Content Writer,"As a Content Writer, you will create written m...",0

In [21]:
df = pd.get_dummies(df, columns=["Gender","Race","Ethnicity"], drop_first=True)

In [22]:
df

,Job Applicant Name,Age,Resume,Job Roles,Job Description,Best Match,Gender_Male,Race_Negroid/Black,Race_White/Caucasian,Ethnicity_Caribbean,...,Ethnicity_Irish,Ethnicity_Italian,Ethnicity_Jamaican,Ethnicity_Japanese,Ethnicity_Kenyan,Ethnicity_Korean,Ethnicity_Nigerian,Ethnicity_Polish,Ethnicity_Thai,Ethnicity_Vietnamese
0,Daisuke Mori,29,"Proficient in Injury Prevention, Motivation, N...",Fitness Coach,A Fitness Coach is responsible for helping cl...,0,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,Taichi Shimizu,31,"Proficient in Healthcare, Pharmacology, Medica...",Physician,"Diagnose and treat illnesses, prescribe medica...",0,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Sarah Martin,46,"Proficient in Forecasting, Financial Modelling...",Financial Analyst,"As a Financial Analyst, you will be responsibl...",0,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,Keith Hughes,43,"Proficient in Budgeting, Supply Chain Optimiza...",Supply Chain Manager,A Supply Chain Manager oversees the entire sup...,1,True,True,False,True,...,False,False,False,False,False,False,False,False,False,False
4,James Davis,49,"Proficient in Logistics, Negotiation, Procurem...",Supply Chain Manager,A Supply Chain Manager oversees the entire sup...,1,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Jada Williams,30,"Proficient in Biology, Regulatory Compliance, ...",Biomedical Engineer,A Biomedical Engineer designs and develops med...,0,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
9996,Jaden Carter,52,"Proficient in Communication, Teamwork, Lesson ...",Teacher,A Teacher shapes the future of students by del...,0,True,True,False,False,...,False,False,False,False,False,False,True,False,False,False
9997,Mia Foster,25,"Proficient in Medical Terminology, Critical Th...",Physician,"Diagnose and treat illnesses, prescribe medica...",0,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
9998,Stella Green,51,"Proficient in Exercise Programming, Motivation...",Fitness Coach,A Fitness Coach is responsible for helping cl...,1,False,False,True,False,...,True,False,False,False,False,False,False,False,False,False
9999,Ryo Nishida,46,"Proficient in Content Strategy, Copywriting, C...",Content Writer,"As a Content Writer, you will create written m...",0,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [6]:
# huggingface에서 다운로드
from datasets import load_dataset
dataset = load_dataset("lang-uk/recruitment-dataset-candidate-profiles-english", split="train")

Generating train split: 100%|██████████| 210250/210250 [00:00<00:00, 784132.28 examples/s]

In [12]:
dataset

Dataset({
    features: ['Position', 'Moreinfo', 'Looking For', 'Highlights', 'Primary Keyword', 'English Level', 'Experience Years', 'CV', 'CV_lang', 'id', '__index_level_0__'],
    num_rows: 210250
})