In [1]:
from Crawling.Data_Analysis import *
from Crawling.Wanted_Crawling import *

In [2]:
'''
# Wanted Crawling
원티드 사이트의 메인 홈페이지 공고들으 가져옵니다
해당 공고들의 id값들을 이용해 공고에 접근하고
각 공고의 상세정보를 가져옵니다
'''

posts = get_wanted_main_crawling()

Fetching job posts: 10000post [01:27, 113.84post/s]

In [3]:
posts

[{'id': 283170,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 426,
   'name': '컬리',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/426/kzslm49iecovfi0j__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/426/kzslm49iecovfi0j__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '강남구'},
  'position': '프로모션 \u200b기획 \u200b마케터',
  'category_tag': {'parent_id': 523, 'id': 1033},
  'attraction_tags': [10425,
   10436,
   10405,
   10438,
   10468,
   10409,
   10537,
   10447,
   10420,
   10485,
   10521,
   10426,
   10395],
  'skill_tags': [],
  'user_oriented_tags': [10249,
   10250,
   10378,
   10251,
   10253,
   10382,
   10254,
   10379,
   10385,
   10255,
   10381,
   10252,
   10386,
   10265,
   10266],
  'annual_from': 3,
  'annual_to': 10,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 286101,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 23419,
   'name': '씨제이올리브영(CJ올리브영)',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/23419/f7aifr54bs6x1m9n__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/23419/f7aifr54bs6x1m9n__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '용산구'},
  'position': '커머스디자이너',
  'category_tag': {'parent_id': 511, 'id': 592},
  'attraction_tags': [10433,
   10401,
   10468,
   10405,
   10438,
   10564,
   10440,
   10441,
   10408,
   10537,
   10436,
   10423,
   10425],
  'skill_tags': [],
  'user_oriented_tags': [10251, 10379, 10253],
  'annual_from': 4,
  'annual_to': 11,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 283738,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 3382,
   'name': '111퍼센트',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/3382/hx3cm8ihl6azoja1__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/3382/hx3cm8ihl6azoja1__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '강남구'},
  'position': '웹 프론트 개발자',
  'category_tag': {'parent_id': 518, 'id': 669},
  'attraction_tags': [10403,
   10436,
   10437,
   10440,
   10408,
   10537,
   10447,
   10418,
   10423,
   10398],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10246,
   10247,
   10377,
   10249,
   10251,
   10380,
   10379,
   10253,
   10383,
   10385,
   10265,
   10266],
  'annual_from': 3,
  'annual_to': 100,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 286509,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 137,
   'name': '여기어때컴퍼니',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/137/oqkbo69az563n2fs__1080_790.png',
   'thumb': 'https://static.wanted.co.kr/images/company/137/oqkbo69az563n2fs__400_400.png',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '강남구'},
  'position': 'Product Owner [파트너서비스]',
  'category_tag': {'parent_id': 507, 'id': 559},
  'attraction_tags': [10523,
   10397,
   10401,
   10404,
   10408,
   10537,
   10413,
   10418,
   10423,
   10431,
   10436,
   10437,
   10438,
   10564,
   10440,
   10441,
   10443,
   10468,
   10485,
   10486],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10247,
   10248,
   10377,
   10250,
   10378,
   10249,
   10253,
   10251,
   10383,
   10384,
   10385,
   10379,
   10252,
   10386,
   10265,
   10266],
  'annual_from': 1,
  'annual_to': 5,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 279483,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 25926,
   'name': '토스페이먼츠',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/25926/owr6ikoope0b8prw__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/25926/owr6ikoope0b8prw__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '강남구'},
  'position': 'Frontend Developer',
  'category_tag': {'parent_id': 518, 'id': 669},
  'attraction_tags': [10401,
   10404,
   10436,
   10468,
   10440,
   10408,
   10412,
   10508,
   10511,
   10420,
   10485,
   10424,
   10426,
   10429,
   10399],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10246,
   10248,
   10377,
   10250,
   10378,
   10252,
   10253,
   10380,
   10249,
   10384,
   10385,
   10386,
   10379,
   10251,
   10254,
   10382,
   10265,
   10266],
  'annual_from': 0,
  'annual_to': 100,
  'is_newbie': True,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 285600,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 1343,
   'name': '힐링페이퍼(강남언니)',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/1343/amroyp3jwjcbyg6r__1080_790.png',
   'thumb': 'https://static.wanted.co.kr/images/company/1343/amroyp3jwjcbyg6r__400_400.png',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '강남구'},
  'position': '프로덕트 디자이너 (주니어)',
  'category_tag': {'parent_id': 511, 'id': 10530},
  'attraction_tags': [10521,
   10523,
   10397,
   10401,
   10403,
   10409,
   10537,
   10412,
   10423,
   10425,
   10430,
   10436,
   10437,
   10564,
   10443,
   10445,
   10446,
   10468,
   10486],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10246,
   10248,
   10377,
   10249,
   10251,
   10379,
   10253,
   10381,
   10255,
   10384,
   10385,
   10380,
   10265,
   10266],
  'annual_from': 2,
  'annual_to': 100,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 283875,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 15353,
   'name': '페이타랩(패스오더)',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/15353/ya4dr2v1bfroezwy__1080_790.png',
   'thumb': 'https://static.wanted.co.kr/images/company/15353/ya4dr2v1bfroezwy__400_400.png',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '강남구'},
  'position': '웹 프론트엔드 개발자(JavaScript, React)',
  'category_tag': {'parent_id': 518, 'id': 873},
  'attraction_tags': [10433,
   10401,
   10403,
   10436,
   10437,
   10468,
   10439,
   10408,
   10537,
   10564,
   10445,
   10423,
   10523],
  'skill_tags': [],
  'user_oriented_tags': [10249,
   10250,
   10251,
   10379,
   10253,
   10378,
   10255,
   10381,
   10385,
   10254,
   10382,
   10265,
   10266],
  'annual_from': 0,
  'annual_to': 10,
  'is_newbie': True,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 282656,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 2569,
   'name': '미리디',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/2569/kdyxxgsh74n5gwvk__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/2569/kdyxxgsh74n5gwvk__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '구로구'},
  'position': '[미리캔버스] 프론트엔드 개발자',
  'category_tag': {'parent_id': 518, 'id': 873},
  'attraction_tags': [10509,
   10523,
   10399,
   10401,
   10404,
   10409,
   10537,
   10412,
   10413,
   10426,
   10436,
   10437,
   10564,
   10441,
   10443,
   10447,
   10468,
   10484,
   10485,
   10486],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10246,
   10247,
   10248,
   10249,
   10250,
   10251,
   10380,
   10379,
   10378,
   10383,
   10384,
   10385,
   10253,
   10254,
   10382,
   10252,
   10386,
   10265,
   10266,
   10377],
  'annual_from': 1,
  'annual_to': 5,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 278301,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 23419,
   'name': '씨제이올리브영(CJ올리브영)',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/23419/f7aifr54bs6x1m9n__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/23419/f7aifr54bs6x1m9n__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '용산구'},
  'position': 'UIUX 디자이너(신사업 프로덕트)',
  'category_tag': {'parent_id': 511, 'id': 599},
  'attraction_tags': [10433,
   10401,
   10468,
   10405,
   10438,
   10564,
   10440,
   10441,
   10408,
   10537,
   10436,
   10423,
   10425],
  'skill_tags': [],
  'user_oriented_tags': [10251, 10379, 10253],
  'annual_from': 4,
  'annual_to': 11,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 282809,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 1053,
   'name': '타다(VCNC)',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/1053/1i5oxr3ognd3uxgw__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/1053/1i5oxr3ognd3uxgw__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '성동구'},
  'position': '프로덕트 디자이너(PD)',
  'category_tag': {'parent_id': 511, 'id': 595},
  'attraction_tags': [10433, 10401, 10436, 10468, 10437, 10409, 10423, 10398],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10246,
   10248,
   10377,
   10249,
   10251,
   10380,
   10253,
   10379,
   10250,
   10378,
   10385,
   10384,
   10254,
   10382,
   10264,
   10266],
  'annual_from': 3,
  'annual_to': 7,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 283435,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 46520,
   'name': '토스인컴',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/46520/jpyhiwrbieuakulq__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/46520/jpyhiwrbieuakulq__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '강남구'},
  'position': 'Frontend Developer',
  'category_tag': {'parent_id': 518, 'id': 939},
  'attraction_tags': [10402,
   10436,
   10407,
   10440,
   10508,
   10511,
   10424,
   10426,
   10398],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10248,
   10377,
   10249,
   10251,
   10379,
   10253,
   10252,
   10384,
   10385,
   10386,
   10264,
   10266],
  'annual_from': 2,
  'annual_to': 10,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 284592,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 25926,
   'name': '토스페이먼츠',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/25926/owr6ikoope0b8prw__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/25926/owr6ikoope0b8prw__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '강남구'},
  'position': 'Product Manager',
  'category_tag': {'parent_id': 507, 'id': 559},
  'attraction_tags': [10401,
   10404,
   10436,
   10468,
   10440,
   10408,
   10412,
   10420,
   10485,
   10424,
   10426,
   10429,
   10399],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10246,
   10248,
   10377,
   10250,
   10378,
   10252,
   10253,
   10380,
   10249,
   10384,
   10385,
   10386,
   10379,
   10251,
   10254,
   10382,
   10265,
   10266],
  'annual_from': 3,
  'annual_to': 100,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 287145,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 137,
   'name': '여기어때컴퍼니',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/137/oqkbo69az563n2fs__1080_790.png',
   'thumb': 'https://static.wanted.co.kr/images/company/137/oqkbo69az563n2fs__400_400.png',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '강남구'},
  'position': 'Frontend Engineer [파트너서비스]',
  'category_tag': {'parent_id': 518, 'id': 669},
  'attraction_tags': [10523,
   10397,
   10401,
   10404,
   10408,
   10537,
   10413,
   10418,
   10423,
   10431,
   10436,
   10437,
   10438,
   10564,
   10440,
   10441,
   10443,
   10468,
   10485,
   10486],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10247,
   10248,
   10377,
   10250,
   10378,
   10249,
   10253,
   10251,
   10383,
   10384,
   10385,
   10379,
   10252,
   10386,
   10265,
   10266],
  'annual_from': 3,
  'annual_to': 6,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 282658,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 2569,
   'name': '미리디',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/2569/kdyxxgsh74n5gwvk__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/2569/kdyxxgsh74n5gwvk__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '구로구'},
  'position': '[미리디] 프로덕트 디자이너(UI/UX Designer)',
  'category_tag': {'parent_id': 511, 'id': 597},
  'attraction_tags': [10509,
   10523,
   10399,
   10401,
   10404,
   10409,
   10537,
   10412,
   10413,
   10426,
   10436,
   10437,
   10564,
   10441,
   10443,
   10447,
   10468,
   10484,
   10485,
   10486],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10246,
   10247,
   10248,
   10249,
   10250,
   10251,
   10380,
   10379,
   10378,
   10383,
   10384,
   10385,
   10253,
   10254,
   10382,
   10252,
   10386,
   10265,
   10266,
   10377],
  'annual_from': 3,
  'annual_to': 100,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 282846,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 2221,
   'name': '넷마블',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/2221/wxinzjfpwfkplncw__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/2221/wxinzjfpwfkplncw__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '구로구'},
  'position': '웹 프론트엔드 개발자',
  'category_tag': {'parent_id': 518, 'id': 660},
  'attraction_tags': [10467,
   10404,
   10437,
   10564,
   10468,
   10440,
   10409,
   10413,
   10509,
   10447,
   10485,
   10422,

In [4]:
ids = get_ids(posts)
ids

[283170,
 286101,
 283738,
 286509,
 279483,
 285600,
 283875,
 282656,
 278301,
 282809,
 283435,
 284592,
 287145,
 282658,
 282846,
 282132,
 271805,
 286988,
 279166,
 282831,
 285788,
 284928,
 284431,
 284557,
 284772,
 280236,
 277111,
 283599,
 284161,
 286360,
 285838,
 222071,
 227561,
 287272,
 286471,
 283438,
 281356,
 285036,
 286806,
 280245,
 282655,
 287070,
 288389,
 286506,
 287346,
 286158,
 276130,
 189899,
 280138,
 286462,
 287205,
 281333,
 282533,
 288256,
 278425,
 279823,
 275348,
 283468,
 249296,
 251744,
 270533,
 280758,
 282836,
 283846,
 284888,
 283229,
 279453,
 272871,
 285966,
 276991,
 284788,
 284711,
 283312,
 279405,
 279842,
 233679,
 286457,
 286005,
 281384,
 262948,
 289236,
 216360,
 284114,
 283348,
 254014,
 198858,
 280517,
 284410,
 288097,
 262596,
 284243,
 271186,
 282556,
 284019,
 267690,
 168297,
 287147,
 283918,
 48832,
 263714,
 261137,
 274822,
 277582,
 280688,
 273728,
 274123,
 282256,
 288978,
 246260,
 286919,
 271143,
 283258,
 279062,
 289524,
 274200,
 285489,
 283298,
 284916,
 281396,
 254015,
 285379,
 283747,
 277505,
 286967,
 278634,
 259053,
 283646,
 282961,
 283954,
 287570,
 287055,
 286460,
 283516,
 284910,
 283060,
 226948,
 287163,
 278651,
 235950,
 137664,
 286150,
 285869,
 284443,
 284265,
 285542,
 273278,
 282137,
 202672,
 171712,
 286111,
 285035,
 285067,
 283332,
 278626,
 259187,
 284371,
 284408,
 275967,
 283033,
 244778,
 282782,
 283086,
 279162,
 288454,
 283973,
 283910,
 185388,
 281433,
 284369,
 284436,
 283872,
 283155,
 194059,
 287214,
 250036,
 287697,
 284899,
 276764,
 265906,
 281985,
 259112,
 262802,
 287600,
 289027,
 288171,
 288140,
 287829,
 177802,
 281191,
 283323,
 286296,
 247023,
 279935,
 139067,
 284306,
 282841,
 280199,
 276263,
 288991,
 287699,
 287307,
 196778,
 284809,
 283240,
 281052,
 285795,
 284120,
 283740,
 257306,
 286533,
 287046,
 286373,
 286243,
 283857,
 284319,
 262250,
 249018,
 86060,
 281379,
 273028,
 286192,
 286909,
 276884,
 284301,
 283597,
 202200,
 288892,
 223783,
 287110,
 189909,
 256259,
 287864,
 279434,
 149552,
 282628,
 283320,
 276235,
 281357,
 284115,
 243835,
 276525,
 286057,
 283871,
 279563,
 286246,
 288591,
 287734,
 287019,
 285594,
 282369,
 284914,
 284259,
 283399,
 288929,
 244761,
 288736,
 287293,
 82139,
 285882,
 285628,
 274888,
 286452,
 285461,
 284183,
 284452,
 281355,
 260746,
 289140,
 284110,
 286500,
 229817,
 285668,
 283624,
 282309,
 281477,
 274496,
 289299,
 286883,
 242469,
 288551,
 286140,
 280612,
 287671,
 95385,
 278408,
 287899,
 287851,
 271591,
 287172,
 286901,
 287559,
 255944,
 287680,
 286937,
 286388,
 259159,
 286194,
 281418,
 115547,
 281404,
 230044,
 264056,
 283953,
 282364,
 287206,
 286962,
 282532,
 285020,
 284266,
 283158,
 259396,
 279638,
 277578,
 275176,
 263095,
 284119,
 264057,
 192389,
 283746,
 268174,
 286455,
 287061,
 284915,
 284581,
 283574,
 283408,
 282907,
 44837,
 282940,
 285791,
 287045,
 281109,
 282251,
 285884,
 285475,
 283889,
 283351,
 248679,
 281358,
 288867,
 277475,
 280510,
 279303,
 286769,
 283863,
 285468,
 283758,
 283502,
 282750,
 278524,
 262671,
 282837,
 285649,
 130434,
 286219,
 286207,
 283984,
 284639,
 282871,
 277836,
 282718,
 276047,
 268260,
 264364,
 263613,
 283007,
 206658,
 277770,
 284518,
 287740,
 286534,
 286229,
 285727,
 282559,
 284599,
 178777,
 174830,
 257207,
 278348,
 231568,
 119455,
 276363,
 283263,
 288555,
 288448,
 288177,
 280701,
 287398,
 286868,
 285526,
 283250,
 285113,
 284093,
 277219,
 110433,
 287577,
 286028,
 242470,
 288404,
 287610,
 243652,
 285804,
 285888,
 285079,
 259509,
 282597,
 284370,
 250715,
 283861,
 283019,
 152424,
 282246,
 207573,
 209728,
 264022,
 272953,
 214484,
 268137,
 203912,
 247032,
 284159,
 222550,
 282948,
 285291,
 284931,
 281366,
 284795,
 266969,
 283081,
 277309,
 247240,
 255280,
 260397,
 285831,
 285266,
 283748,
 287367,
 286886,
 285239,
 286459,
 247869,
 238235,
 276168,
 272991,
 272151,
 181466,
 260703,
 209695,
 283083,
 285876,
 289214,
 288771,
 211925,
 272766,
 283319,
 282889,
 287598,
 281568,
 239276,
 260465,
 247595,
 268042,
 283806,
 254630,
 261894,
 265214,
 274256,
 288714,
 284670,
 288019,
 287632,
 286971,
 141545,
 282900,
 279948,
 285206,
 284929,
 284555,
 282996,
 283160,
 282654,
 263167,
 277031,
 254545,
 216514,
 288426,
 283400,
 277639,
 285573,
 285647,
 283035,
 159753,
 282502,
 275940,
 261153,
 281278,
 279187,
 275771,
 270013,
 125138,
 254414,
 288640,
 287791,
 287463,
 287296,
 287232,
 286944,
 286924,
 280711,
 286380,
 251042,
 283193,
 285663,
 281945,
 213554,
 282017,
 284376,
 284150,
 283804,
 283372,
 280489,
 281387,
 280550,
 276453,
 272199,
 253531,
 252404,
 865,
 265025,
 284496,
 263480,
 287185,
 287870,
 287551,
 287152,
 286805,
 286602,
 270765,
 286260,
 286020,
 285798,
 263820,
 285552,
 284495,
 283880,
 283215,
 283137,
 126670,
 277167,
 238949,
 57779,
 274478,
 287303,
 274872,
 285238,
 286969,
 284466,
 280077,
 286401,
 285464,
 285610,
 197921,
 285397,
 262627,
 270159,
 283546,
 283581,
 198382,
 281460,
 281867,
 217834,
 280196,
 279551,
 278593,
 276062,
 271443,
 270067,
 272839,
 265166,
 288541,
 284402,
 282280,
 272208,
 287690,
 281977,
 287006,
 283835,
 213717,
 284501,
 284157,
 283407,
 279145,
 262418,
 282859,
 281222,
 261317,
 280929,
 260018,
 278290,
 225171,
 276118,
 275491,
 267761,
 75323,
 281528,
 286082,
 285995,
 287930,
 288167,
 288050,
 287941,
 287858,
 280474,
 273980,
 284374,
 249574,
 286254,
 278733,
 30767,
 283735,
 279210,
 285782,
 271447,
 281365,
 284700,
 284448,
 283639,
 273820,
 278277,
 283648,
 280524,
 272927,
 280669,
 281273,
 287847,
 287741,
 287688,
 281271,
 256339,
 285765,
 275641,
 284325,
 285886,
 284734,
 284637,
 272687,
 282868,
 282762,
 248771,
 162405,
 279200,
 278860,
 257214,
 220057,
 235952,
 173289,
 235501,
 284950,
 283434,
 264990,
 271837,
 284317,
 287839,
 287700,
 245557,
 285979,
 286139,
 284759,
 284997,
 284525,
 283730,
 284111,
 281464,
 283878,
 259032,
 282501,
 281342,
 280960,
 280829,
 279873,
 275817,
 269006,
 193258,
 56331,
 287072,
 282581,
 288668,
 288334,
 287188,
 284260,
 277454,
 259939,
 287454,
 287319,
 285096,
 286350,
 265668,
 270110,
 285635,
 284006,
 280030,
 285187,
 280140,
 284000,
 283911,
 283825,
 281506,
 279919,
 279515,
 278302,
 270299,
 264624,
 278013,
 288615,
 288806,
 283371,
 288661,
 287621,
 282235,
 287049,
 218967,
 271142,
 285990,
 284944,
 285806,
 281468,
 285784,
 285162,
 285431,
 280621,
 284084,
 283093,
 274293,
 273799,
 277224,
 273420,
 253017,
 282662,
 286173,
 237469,
 190225,
 284474,
 288485,
 288127,
 284830,
 229077,
 185551,
 279651,
 287453,
 282224,
 286483,
 287327,
 287308,
 287039,
 283647,
 281116,
 269876,
 284662,
 279829,
 285171,
 285434,
 285084,
 270523,
 284439,
 284392,
 267405,
 282521,
 282800,
 282365,
 282278,
 281491,
 280137,
 278705,
 278135,
 272456,
 84876,
 265111,
 238086,
 866,
 207345,
 285603,
 289402,
 284937,
 194945,
 285047,
 263476,
 287673,
 287234,
 286058,
 284113,
 286978,
 210740,
 286393,
 286100,
 88904,
 236175,
 285729,
 285546,
 281402,
 284617,
 284311,
 284194,
 283710,
 283277,
 283172,
 283057,
 282573,
 282466,
 281859,
 234830,
 266757,
 269975,
 277330,
 276993,
 273191,
 252123,
 260951,
 188531,
 250124,
 269641,
 286235,
 275453,
 283373,
 278410,
 286282,
 287920,
 29390,
 288075,
 287824,
 288051,
 287567,
 287311,
 286880,
 190204,
 265951,
 279921,
 286342,
 278155,
 286012,
 285562,
 272996,
 283593,
 284648,
 284634,
 284456,
 271310,
 283654,
 282788,
 282342,
 118971,
 272333,
 261407,
 283347,
 289519,
 289413,
 285232,
 180371,
 283480,
 287274,
 279610,
 288568,
 262946,
 253400,
 287498,
 266750,
 282272,
 287643,
 258803,
 287449,
 287060,
 286968,
 286798,
 286679,
 285673,
 285527,
 285004,
 270770,
 285189,
 283956,
 284457,
 277428,
 247201,
 283772,
 248675,
 283552,
 283078,
 282730,
 233010,
 281757,
 278427,
 278872,
 278739,
 274532,
 271352,
 252542,
 195143,
 265316,
 288845,
 284532,
 288526,
 282817,
 287933,
 276689,
 286261,
 287222,
 287157,
 287066,
 287024,
 286702,
 237159,
 286646,
 286108,
 284996,
 285974,
 271667,
 282125,
 285891,
 282165,
 285470,
 283883,
 285398,
 285342,
 285325,
 285260,
 285078,
 284669,
 284646,
 279189,
 284454,
 284323,
 277249,
 283525,
 283009,
 282797,
 282610,
 279695,
 223157,
 263448,
 278082,
 276294,
 265030,
 257253,
 246286,
 11112,
 283651,
 264050,
 269150,
 274816,
 272858,
 289012,
 288869,
 280666,
 264259,
 278734,
 285843,
 287566,
 287455,
 287466,
 287192,
 285041,
 252451,
 279939,
 272675,
 261286,
 286599,
 259157,
 286008,
 286007,
 285918,
 281866,
 285145,
 285023,
 284894,
 232990,
 259483,
 260072,
 283769,
 280466,
 283479,
 274639,
 284005,
 283749,
 282732,
 282663,
 278793,
 253089,
 237445,
 276982,
 191444,
 279385,
 273991,
 274032,
 243834,
 260009,
 254411,
 268302,
 211331,
 281453,
 289159,
 265076,
 ...]

In [5]:
post_detail = get_wanted_detail_crawling(ids)

Fetching Detail Contents:  96%|█████████▌| 9552/10000 [42:02<02:29,  2.99post/s]  WARNING:root:jid=286911 status 503 → retry in 1.9s
Fetching Detail Contents: 100%|██████████| 10000/10000 [44:03<00:00,  3.78post/s]

In [6]:
post_detail

,position,intro,main_tasks,requirements,preferred_points,benefits,hire_rounds,attraction,company,country,location,district,category_parent,category_child,skill,annual_from,annual_to,is_newbie,due_time,job_id
0,프로모션 ​기획 ​마케터,컬리 온사이트 ​마케팅 조직은 고객이 컬리에서 ​즐거운 ​장보기 경험을 ​하도록 돕...,사업 목표 달성을 위한 온사이트 프로모션 전략 수립 및 실행\n\n1) 연/분기/월...,[경험]\n• 최소 1년 이상의 유관 경험 또는 그에 준하는 역량을 보유하신 분\n...,"• Amplitude 활용이 가능하신 분\n• 서비스 마케팅, 사업 전략까지 확장 ...","모두가 집중하고 성장할 수 있도록, 최적의 근무 환경을 제공해요\n \n• 리프레시...",[합류 여정]\n지원서 제출 ＞직무 적합성 인터뷰 ＞ 직무적합성검사 및 종합 인터뷰...,"[의료비지원, 휴가비, 유급휴가, 커피·스낵바, 1,001~10,000명, 설립10...",컬리,한국,서울,강남구,마케팅·광고,"[마케터, 디지털 마케터, 모바일마케팅]",[],3,10,False,None,283170
1,커머스디자이너,"All Live Better,\n\nNo.1 헬스&뷰티 스토어 올리브영은 20년 이...","• 올리브영 온라인몰 시즌별, 이벤트별 프로모션 그래픽 디자인\n• 스토리텔링 중심...",* 포트폴리오 필수 제출 바랍니다.\n\n• 커머스 및 프로모션 디자인에 대한 실무...,• 디자인 관련 전공 혹은 그에 준하는 경험을 보유하신 분\n• 디자인 시스템 또는...,• CJ그룹 계열사 인프라 40% 할인\n• 카페테리아 포인트(현금성 복지 포인트)...,※ 전형 안내\n서류전형 - 1차 인터뷰 - 온라인 인성검사 - 2차 인터뷰 - R...,"[휴가비, 의료비지원, 건강검진지원, 편의시설, 자기계발지원, 수평적조직, 설립4~...",씨제이올리브영(CJ올리브영),한국,서울,용산구,디자인,"[그래픽 디자이너, UI,GUI 디자이너, 콘텐츠 디자이너]",[],4,11,False,None,286101
2,웹 프론트 개발자,"111퍼센트는 재미라는 본질에 집중합니다. \n재미는 심플하고, 참신한 룰에서 나옵...",• 사내 인하우스툴의 프론트엔드 신규개발 및 유지보수(React)를 담당합니다.\n...,• React 개발 실무 경력 3년 이상 또는 그에 준하는 역량을 보유하신 분을 찾...,• WebGL과 같이 다양한 형태의 웹 프론트 개발 경험이 있으신 분이면 더 좋습니...,"• 전사 겨울 방학(매년 크리스마스~신정)\n• 점심 식대 최대 12,000원 지원...",* 서류전형 ＞ 1차 인터뷰(직무) ＞ 2차 인터뷰(컬처핏) ＞ 처우 협상 ＞ 최...,"[편의시설, 건강검진지원, 커피·스낵바, 식대지원, 51~300명, 설립4~9년, ...",111퍼센트,한국,서울,강남구,개발,[프론트엔드 개발자],[],3,100,False,None,283738
3,Product Owner [파트너서비스],| 여기어때 ​'Product ​Owner ​[파트너서비스]'를 소개해요\n• Pa...,"• 숙박 등 다양한 도메인과 협업을 통한 파트너 플랫폼(파트너 어드민, 내부 운영 ...","• 포트폴리오 제출 필수 (PDF 파일 혹은 링크 첨부 가능, Zip 파일 불가)\...",• 국내외 주요 이커머스 서비스의 백오피스/셀러오피스 경험이 있는 분\n• 데이터 ...,1. WORK&LIFE\n• 월요일 1시 출근 : 여유있는 한 주의 시작\n• 자율...,• 서류 전형 ＞ 1차 인터뷰 ＞ 2차 인터뷰 ＞ 처우 협의 ＞ 입사 확정\n• 상...,"[사내동호회, 휴가비, 식대지원, 커피·스낵바, 건강검진지원, 편의시설, 수평적조직...",여기어때컴퍼니,한국,서울,강남구,경영·비즈니스,[PM·PO],[],1,5,False,None,286509
4,Frontend Developer,[꼭 확인해 주세요]\n•이력서 및 제출 서류에 허위 사실이 발견되거나 근무 이력 ...,[지금까진 이런 일을 했어요]\n•누구나 쉽게 원하는 결제 경험을 만들 수 있도록 ...,[이런 분과 함께하고 싶어요]\n•개발자 경험에 대해 높은 가치를 두고 있는 분\n...,"[이런 경험이 있다면 이력서에 꼭 작성해 주세요]\n•TypeScript, Flow...",[이렇게 일해요]\n• 자율과 책임의 문화: 토스는 Manager가 아닌 Maker...,[토스페이먼츠로의 합류 여정]\n•서류접수 ＞ 사전 과제 ＞ 직무 인터뷰 ＞ 문화적...,"[단체보험, 편의시설, 보너스, 커피·스낵바, 설립4~9년, 유급휴가, 301~1,...",토스페이먼츠,한국,서울,강남구,개발,[프론트엔드 개발자],[],0,100,True,2025-06-30,279483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,NPU Firmware Engineer,"[회사 소개]\n오픈엣지는 인공지능 기술을 더 많은 사람들이, 더 가까이에서 누릴 ...",• 신경망 연산자별 NPU 연산 Firmware 개발\n• Firmware에 대한 ...,[자격 요건]\n• 경력: 석사 이상의 학력 또는 2년 이상 해당 전문 분야 종사\...,"• 반도체 및 컴퓨터, 전기/전자학과 석/박사 학위\n• RVV (RISC-V Ve...","• 업무 방식: 자율 출퇴근 (선택적 근로시간제), 자율적 업무 환경, 수평적 조직...",• 서류 접수 ＞ 1차 직무 인터뷰 ＞ 2차 리더십 인터뷰 ＞ 최종 합격,"[자기계발지원, 커피·스낵바, 유망산업, 식대지원, 의료비지원, 건강검진지원, 연봉...",오픈엣지테크놀로지,한국,서울,강남구,개발,"[C,C++ 개발자]","[C, C++, 협력, CUDA]",4,14,False,None,240865
9996,NPU RISC-V Core Processor Engineer,"[회사 소개]\n오픈엣지는 인공지능 기술을 더 많은 사람들이, 더 가까이에서 누릴 ...",• AI Processor 마이크로 아키텍쳐 (Micro-architecture) ...,[자격 요건]\n• 경력: 4년 이상 해당 전문 분야 종사\n• 전자공학 또는 컴퓨...,• CPU/GPU/NPU 개발 경험이 있으신 분\n• Computer System ...,"• 업무 방식: 자율 출퇴근 (선택적 근로시간제), 자율적 업무 환경, 수평적 조직...",• 서류 접수 ＞ 1차 직무 인터뷰 ＞ 2차 리더십 인터뷰 ＞ 최종 합격,"[자기계발지원, 커피·스낵바, 유망산업, 식대지원, 의료비지원, 건강검진지원, 연봉...",오픈엣지테크놀로지,한국,서울,강남구,엔지니어링·설계,[전자 엔지니어],"[Verilog, RTL 설계]",4,14,False,None,240862
9997,NPU RTL Design Engineer,"[회사 소개]\n오픈엣지는 인공지능 기술을 더 많은 사람들이, 더 가까이에서 누릴 ...",• NPU 구조 설계\n• NPU RTL 검증 환경 개발 및 IP 검증,[필요 스킬]\n• RTL 설계 경험 (Verilog/SystemVerilog 설계...,• NPU/GPU 개발 경험\n• Computer Architecture에 대한 지...,"• 업무 방식: 자율 출퇴근 (선택적 근로시간제), 자율적 업무 환경, 수평적 조직...",• 제출서류 : 이력서 1부 (자유양식)\n• 채용절차 : 서류 접수 ＞ 1차 ...,"[자기계발지원, 커피·스낵바, 유망산업, 식대지원, 의료비지원, 건강검진지원, 연봉...",오픈엣지테크놀로지,한국,서울,강남구,엔지니어링·설계,"[전기기계 공학자, 전자 엔지니어]","[Verilog, RTL 설계, RTL 코딩, RTL 검증]",4,10,False,None,240849
9998,롯데면세점 명품관 세븐에잇언더 판매사원,롯데면세점 명품관 10층 세븐에잇언더 판매 사원,• 스토어 관리 및 제품 판매,"• 일상 중국어 회화 가능자(2명), 일본어 가능자(1명)\n• 브랜드 이해와 직원...",• 면세점 판촉 경험자,• 자사 상품 할인 혜택,,"[50명이하, 설립3년이하, 외국인 지원 가능]",더블유엠더블유(WMW),한국,서울,중구,영업,[해외영업],[],0,1,True,None,240784
9999,데이터 엔지니어,앞으로의 소비는 자신이 감당할 수 있는 금액 안에서 필요한 제품을 얼마나 살 수 있...,셰어라운드의 데이터 엔지니어는 서비스를 위한 데이터 플랫폼 및 신용심사모형 설계 및...,"• 유관 경력 5년 이상\n• Java, Kotlin, Scala, Python 중...",■ 정규직 : 셰어라운드의 문화와 비전에 맞는지 확인하기 위해 6개월 수습기간 있음...,"셰어라운드는 일을 잘 할 수 있는, 일하기 좋은, 일하는 팀원이 만족하는 회사를 만...",,"[커피·스낵바, 자기계발지원, 50명이하, 설립4~9년]",셰어라운드,한국,서울,종로구,개발,"[데이터 엔지니어, 서버 개발자, 데이터 사이언티스트]","[iOS, Kotlin, Python, Scala, SQL, AWS, Spring ...",5,10,False,None,161537

In [7]:
post_detail.to_json('../Data_Files/wanted_detail_20250616.txt', force_ascii=False)

In [8]:
post_improve_detail = toImproveDataFrame(post_detail)

In [9]:
split_columns = ['main_tasks', 'requirements', 'preferred_points', 'benefits', 'hire_rounds']

for column in split_columns:
    post_improve_detail[column] = post_improve_detail[column].apply(
        lambda x: x.split('\n') if isinstance(x, str) else x)

post_improve_detail.drop(columns=['country'], inplace=True)

In [10]:
post_improve_detail.drop_duplicates(subset=['position'], inplace=True)

In [11]:
post_improve_detail.set_index('job_id', inplace=True)

In [12]:
columns = post_improve_detail.columns
columns = columns.tolist()
for col in columns:
    post_improve_detail[col] = post_improve_detail[col].apply(
        lambda x: x.replace('\n', '') if isinstance(x, str) else x)

In [13]:
post_improve_detail.rename(columns={
    'position': '제목',
    'intro': '포지션 상세 설명',
    'main_tasks': '주요 업무',
    'requirements': '자격 요건',
    'preferred_points': '우대 사항',
    'benefits': '복지',
    'hire_rounds': '채용절차',
    'attraction': '특징',
    'company': '회사명',
    'location': '근무지',
    'district': '지역',
    'category_parent': '직군',
    'category_child': '직무',
    'skill': '기술 스택',
    'annual_from': '요구 최소 경력',
    'annual_to': '요구 최대 경력',
    'is_newbie': '신입 지원 가능 여부',
    'due_time': '마감일',
}, inplace=True)

In [14]:
import numpy as np

# 공백·탭·개행 모두 제거한 뒤 '' 이면 상시 공고
post_improve_detail["마감일"] = np.where(
    post_improve_detail["마감일"].astype(str).str.strip() == "",
    "상시 공고",
    post_improve_detail["마감일"]
)

post_improve_detail.drop(columns=['요구 최대 경력'], inplace=True)

In [26]:
post_improve_detail

,제목,포지션 상세 설명,주요 업무,자격 요건,우대 사항,복지,채용절차,특징,회사명,근무지,지역,직군,직무,기술 스택,요구 최소 경력,신입 지원 가능 여부,마감일
283170,프로모션 기획 마케터,컬리 온사이트 마케팅 조직은 고객이 컬리에서 즐거운 장보기 경험을 하도록 돕고 그에...,"[사업 목표 달성을 위한 온사이트 프로모션 전략 수립 및 실행, , 1 연분기월 별...","[경험, 최소 1년 이상의 유관 경험 또는 그에 준하는 역량을 보유하신 분, 경...","[Amplitude 활용이 가능하신 분, 서비스 마케팅, 사업 전략까지 확장 가능...","[모두가 집중하고 성장할 수 있도록, 최적의 근무 환경을 제공해요, , 리프레시...","[합류 여정, 지원서 제출 직무 적합성 인터뷰 직무적합성검사 및 종합 인터뷰 최...","[의료비지원, 휴가비, 유급휴가, 커피스낵바, 1,00110,000명, 설립10년이...",컬리,서울,강남구,마케팅광고,"[마케터, 디지털 마케터, 모바일마케팅]",[],3,False,상시 공고
286101,커머스디자이너,"All Live Better,No1 헬스뷰티 스토어 올리브영은 20년 이상 축적된 ...","[올리브영 온라인몰 시즌별, 이벤트별 프로모션 그래픽 디자인, 스토리텔링 중심의 ...","[포트폴리오 필수 제출 바랍니다, , 커머스 및 프로모션 디자인에 대한 실무 경험...","[디자인 관련 전공 혹은 그에 준하는 경험을 보유하신 분, 디자인 시스템 또는 U...","[CJ그룹 계열사 인프라 40 할인, 카페테리아 포인트현금성 복지 포인트혜택 개인...","[전형 안내, 서류전형 1차 인터뷰 온라인 인성검사 2차 인터뷰 Refere...","[휴가비, 의료비지원, 건강검진지원, 편의시설, 자기계발지원, 수평적조직, 설립49...",씨제이올리브영CJ올리브영,서울,용산구,디자인,"[그래픽 디자이너, UI,GUI 디자이너, 콘텐츠 디자이너]",[],4,False,상시 공고
283738,웹 프론트 개발자,"111퍼센트는 재미라는 본질에 집중합니다 재미는 심플하고, 참신한 룰에서 나옵니다 ...","[사내 인하우스툴의 프론트엔드 신규개발 및 유지보수React를 담당합니다, Rea...",[React 개발 실무 경력 3년 이상 또는 그에 준하는 역량을 보유하신 분을 찾습...,[WebGL과 같이 다양한 형태의 웹 프론트 개발 경험이 있으신 분이면 더 좋습니다...,"[전사 겨울 방학매년 크리스마스신정, 점심 식대 최대 12,000원 지원, 야근...","[서류전형 1차 인터뷰직무 2차 인터뷰컬처핏 처우 협상 최종합격, 파일 ...","[편의시설, 건강검진지원, 커피스낵바, 식대지원, 51300명, 설립49년, 연봉상...",111퍼센트,서울,강남구,개발,[프론트엔드 개발자],[],3,False,상시 공고
286509,Product Owner 파트너서비스,여기어때 Product Owner 파트너서비스를 소개해요 Partner Lab은 여...,"[숙박 등 다양한 도메인과 협업을 통한 파트너 플랫폼파트너 어드민, 내부 운영 어드...","[포트폴리오 제출 필수 PDF 파일 혹은 링크 첨부 가능, Zip 파일 불가, 최...","[국내외 주요 이커머스 서비스의 백오피스셀러오피스 경험이 있는 분, 데이터 분석 ...","[1 WORKLIFE, 월요일 1시 출근 여유있는 한 주의 시작, 자율형 시차...","[서류 전형 1차 인터뷰 2차 인터뷰 처우 협의 입사 확정, 상기 절차는 ...","[사내동호회, 휴가비, 식대지원, 커피스낵바, 건강검진지원, 편의시설, 수평적조직,...",여기어때컴퍼니,서울,강남구,경영비즈니스,[PMPO],[],1,False,상시 공고
279483,Frontend Developer,꼭 확인해 주세요이력서 및 제출 서류에 허위 사실이 발견되거나 근무 이력 중 징계사...,"[지금까진 이런 일을 했어요, 누구나 쉽게 원하는 결제 경험을 만들 수 있도록 치열...","[이런 분과 함께하고 싶어요, 개발자 경험에 대해 높은 가치를 두고 있는 분, 자동...","[이런 경험이 있다면 이력서에 꼭 작성해 주세요, TypeScript, Flow를 ...","[이렇게 일해요, 자율과 책임의 문화 토스는 Manager가 아닌 Maker들로 ...","[토스페이먼츠로의 합류 여정, 서류접수 사전 과제 직무 인터뷰 문화적합성 인터...","[단체보험, 편의시설, 보너스, 커피스낵바, 설립49년, 유급휴가, 3011,000...",토스페이먼츠,서울,강남구,개발,[프론트엔드 개발자],[],0,True,20250630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240867,NPU Network Optimization Engineer,"회사 소개오픈엣지는 인공지능 기술을 더 많은 사람들이, 더 가까이에서 누릴 수 있도...","[PTQQATPruning 등 신경망 경량화 기법 개발, NPU HW를 고려한 신...","[자격 요건, 경력 석사 이상의 학력 또는 2년 이상 해당 전문 분야 종사, 해...","[반도체 및 컴퓨터, 전기전자학과 석박사 학위, NPU SW Toolkit 개발 ...","[업무 방식 자율 출퇴근 선택적 근로시간제, 자율적 업무 환경, 수평적 조직 문화 ...",[서류 접수 1차 직무 인터뷰 2차 리더십 인터뷰 최종 합격],"[자기계발지원, 커피스낵바, 유망산업, 식대지원, 의료비지원, 건강검진지원, 연봉상...",오픈엣지테크놀로지,서울,강남구,개발,"[C,C++ 개발자]","[Git, PyTorch, Tensorflow, 협력]",2,False,상시 공고
240865,NPU Firmware Engineer,"회사 소개오픈엣지는 인공지능 기술을 더 많은 사람들이, 더 가까이에서 누릴 수 있도...","[신경망 연산자별 NPU 연산 Firmware 개발, Firmware에 대한 검증...","[자격 요건, 경력 석사 이상의 학력 또는 2년 이상 해당 전문 분야 종사, 해...","[반도체 및 컴퓨터, 전기전자학과 석박사 학위, RVV RISCV Vector E...","[업무 방식 자율 출퇴근 선택적 근로시간제, 자율적 업무 환경, 수평적 조직 문화 ...",[서류 접수 1차 직무 인터뷰 2차 리더십 인터뷰 최종 합격],"[자기계발지원, 커피스낵바, 유망산업, 식대지원, 의료비지원, 건강검진지원, 연봉상...",오픈엣지테크놀로지,서울,강남구,개발,"[C,C++ 개발자]","[C, C++, 협력, CUDA]",4,False,상시 공고
240862,NPU RISCV Core Processor Engineer,"회사 소개오픈엣지는 인공지능 기술을 더 많은 사람들이, 더 가까이에서 누릴 수 있도...","[AI Processor 마이크로 아키텍쳐 Microarchitecture 개발, ...","[자격 요건, 경력 4년 이상 해당 전문 분야 종사, 전자공학 또는 컴퓨터공학 ...","[CPUGPUNPU 개발 경험이 있으신 분, Computer System Arch...","[업무 방식 자율 출퇴근 선택적 근로시간제, 자율적 업무 환경, 수평적 조직 문화 ...",[서류 접수 1차 직무 인터뷰 2차 리더십 인터뷰 최종 합격],"[자기계발지원, 커피스낵바, 유망산업, 식대지원, 의료비지원, 건강검진지원, 연봉상...",오픈엣지테크놀로지,서울,강남구,엔지니어링설계,[전자 엔지니어],"[Verilog, RTL 설계]",4,False,상시 공고
240849,NPU RTL Design Engineer,"회사 소개오픈엣지는 인공지능 기술을 더 많은 사람들이, 더 가까이에서 누릴 수 있도...","[NPU 구조 설계, NPU RTL 검증 환경 개발 및 IP 검증]","[필요 스킬, RTL 설계 경험 VerilogSystemVerilog 설계 및 S...","[NPUGPU 개발 경험, Computer Architecture에 대한 지식경험...","[업무 방식 자율 출퇴근 선택적 근로시간제, 자율적 업무 환경, 수평적 조직 문화,...","[제출서류 이력서 1부 자유양식, 채용절차 서류 접수 1차 인터뷰 2차 ...","[자기계발지원, 커피스낵바, 유망산업, 식대지원, 의료비지원, 건강검진지원, 연봉상...",오픈엣지테크놀로지,서울,강남구,엔지니어링설계,"[전기기계 공학자, 전자 엔지니어]","[Verilog, RTL 설계, RTL 코딩, RTL 검증]",4,False,상시 공고
240784,롯데면세점 명품관 세븐에잇언더 판매사원,롯데면세점 명품관 10층 세븐에잇언더 판매 사원,[스토어 관리 및 제품 판매],"[일상 중국어 회화 가능자2명, 일본어 가능자1명, 브랜드 이해와 직원 커뮤니케이...",[면세점 판촉 경험자],[자사 상품 할인 혜택],[],"[50명이하, 설립3년이하, 외국인 지원 가능]",더블유엠더블유WMW,서울,중구,영업,[해외영업],[],0,True,상시 공고

In [17]:
#post_improve_detail.T.to_json('../../Data_Files/wanted_detail_improve_20250515.txt', force_ascii=False)
post_improve_detail.T.to_json('../Data_Files/wanted_detail_improve_20250616.json', force_ascii=False)

In [21]:
with open('../Data_Files/wanted_detail_improve_20250616.json', 'r', encoding='utf-8') as f:
    post_improve_detail = json.load(f)

In [ ]:
with open('../../wanted_detail_improve_20250616.json', 'w', encoding='utf-8') as f:
    json.dump(post_improve_detail, f, ensure_ascii=False, indent=4)