In [1]:
from Source_Files.Crawling.Wanted_Crawling import *
from Source_Files.Crawling.Data_Analysis import *

In [2]:
'''
# Wanted Crawling
원티드 사이트의 메인 홈페이지 공고들으 가져옵니다
해당 공고들의 id값들을 이용해 공고에 접근하고
각 공고의 상세정보를 가져옵니다
'''

posts = get_wanted_main_crawling()

Fetching job posts: 9846post [01:27, 112.85post/s]

In [3]:
posts

[{'id': 283170,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 426,
   'name': '컬리',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/426/kzslm49iecovfi0j__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/426/kzslm49iecovfi0j__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '강남구'},
  'position': '프로모션 \u200b기획 \u200b마케터',
  'category_tag': {'parent_id': 523, 'id': 1033},
  'attraction_tags': [10425,
   10436,
   10405,
   10438,
   10468,
   10409,
   10537,
   10447,
   10420,
   10485,
   10486,
   10521,
   10426,
   10395],
  'skill_tags': [],
  'user_oriented_tags': [10249,
   10250,
   10378,
   10251,
   10253,
   10382,
   10254,
   10379,
   10385,
   10255,
   10381,
   10252,
   10386,
   10265,
   10266],
  'annual_from': 3,
  'annual_to': 10,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 282132,
  'reward_total': '20만원',
  'is_bookmark': False,
  'company': {'id': 102,
   'name': '우아한형제들(배달의민족)',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/102/lhnzt8yqwqslevr1__1080_790.png',
   'thumb': 'https://static.wanted.co.kr/images/company/102/lhnzt8yqwqslevr1__400_400.png',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '송파구'},
  'position': '콘텐츠 에디터',
  'category_tag': {'parent_id': 523, 'id': 1635},
  'attraction_tags': [10400,
   10436,
   10405,
   10468,
   10439,
   10409,
   10537,
   10412,
   10413,
   10509,
   10422,
   10486,
   10424,
   10426,
   10427,
   10430,
   10397,
   10462],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10247,
   10248,
   10377,
   10250,
   10378,
   10249,
   10253,
   10251,
   10383,
   10384,
   10385,
   10379,
   10254,
   10382,
   10265,
   10266],
  'annual_from': 0,
  'annual_to': 100,
  'is_newbie': True,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 100000,
   'reward_recommendee': 100000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '20만원',
   'formatted_recommender': '10만원',
   'formatted_recommendee': '10만원'},
  'employment_type': 'contract',
  'additional_apply_type': None},
 {'id': 282809,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 1053,
   'name': '타다(VCNC)',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/1053/1i5oxr3ognd3uxgw__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/1053/1i5oxr3ognd3uxgw__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '성동구'},
  'position': '프로덕트 디자이너(PD)',
  'category_tag': {'parent_id': 511, 'id': 595},
  'attraction_tags': [10433, 10401, 10436, 10468, 10437, 10409, 10423, 10398],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10246,
   10248,
   10377,
   10249,
   10251,
   10380,
   10253,
   10379,
   10250,
   10378,
   10385,
   10384,
   10254,
   10382,
   10264,
   10266],
  'annual_from': 3,
  'annual_to': 7,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 278301,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 23419,
   'name': '씨제이올리브영(CJ올리브영)',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/23419/f7aifr54bs6x1m9n__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/23419/f7aifr54bs6x1m9n__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '용산구'},
  'position': 'UIUX 디자이너(신사업 프로덕트)',
  'category_tag': {'parent_id': 511, 'id': 599},
  'attraction_tags': [10433,
   10401,
   10468,
   10405,
   10438,
   10564,
   10440,
   10441,
   10408,
   10537,
   10436,
   10486,
   10423,
   10425],
  'skill_tags': [],
  'user_oriented_tags': [10251, 10379, 10253],
  'annual_from': 4,
  'annual_to': 11,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 279483,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 25926,
   'name': '토스페이먼츠',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/25926/owr6ikoope0b8prw__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/25926/owr6ikoope0b8prw__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '강남구'},
  'position': 'Frontend Developer',
  'category_tag': {'parent_id': 518, 'id': 669},
  'attraction_tags': [10401,
   10404,
   10436,
   10468,
   10440,
   10408,
   10412,
   10508,
   10511,
   10420,
   10485,
   10486,
   10424,
   10426,
   10429,
   10399],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10246,
   10248,
   10377,
   10250,
   10378,
   10252,
   10253,
   10380,
   10249,
   10384,
   10385,
   10386,
   10379,
   10251,
   10254,
   10382,
   10265,
   10266],
  'annual_from': 0,
  'annual_to': 100,
  'is_newbie': True,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 282658,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 2569,
   'name': '미리디',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/2569/kdyxxgsh74n5gwvk__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/2569/kdyxxgsh74n5gwvk__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '구로구'},
  'position': '[미리디] 프로덕트 디자이너(UI/UX Designer)',
  'category_tag': {'parent_id': 511, 'id': 597},
  'attraction_tags': [10509,
   10523,
   10399,
   10401,
   10404,
   10409,
   10537,
   10412,
   10413,
   10426,
   10436,
   10437,
   10564,
   10441,
   10443,
   10447,
   10468,
   10484,
   10485,
   10486],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10246,
   10247,
   10248,
   10249,
   10250,
   10251,
   10380,
   10379,
   10378,
   10383,
   10384,
   10385,
   10253,
   10254,
   10382,
   10252,
   10386,
   10265,
   10266,
   10377],
  'annual_from': 0,
  'annual_to': 100,
  'is_newbie': True,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 282656,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 2569,
   'name': '미리디',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/2569/kdyxxgsh74n5gwvk__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/2569/kdyxxgsh74n5gwvk__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '구로구'},
  'position': '[미리캔버스] 프론트엔드 개발자',
  'category_tag': {'parent_id': 518, 'id': 873},
  'attraction_tags': [10509,
   10523,
   10399,
   10401,
   10404,
   10409,
   10537,
   10412,
   10413,
   10426,
   10436,
   10437,
   10564,
   10441,
   10443,
   10447,
   10468,
   10484,
   10485,
   10486],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10246,
   10247,
   10248,
   10249,
   10250,
   10251,
   10380,
   10379,
   10378,
   10383,
   10384,
   10385,
   10253,
   10254,
   10382,
   10252,
   10386,
   10265,
   10266,
   10377],
  'annual_from': 1,
  'annual_to': 5,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 280236,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 2331,
   'name': '케이티밀리의서재',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/2331/x16itycnlsqhg0zo__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/2331/x16itycnlsqhg0zo__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '마포구'},
  'position': '브랜드 & 콘텐츠 디자이너',
  'category_tag': {'parent_id': 511, 'id': 592},
  'attraction_tags': [10433,
   10401,
   10403,
   10468,
   10408,
   10537,
   10447,
   10420,
   10485,
   10486,
   10523,
   10398],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10377,
   10250,
   10378,
   10249,
   10253,
   10251,
   10379,
   10254,
   10385,
   10382,
   10265,
   10266],
  'annual_from': 5,
  'annual_to': 10,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 282846,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 2221,
   'name': '넷마블',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/2221/wxinzjfpwfkplncw__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/2221/wxinzjfpwfkplncw__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '구로구'},
  'position': '웹 프론트엔드 개발자',
  'category_tag': {'parent_id': 518, 'id': 660},
  'attraction_tags': [10467,
   10404,
   10437,
   10564,
   10468,
   10440,
   10409,
   10413,
   10509,
   10447,
   10485,
   10422,
   10486,
   10425,
   10427,
   10396],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10377,
   10249,
   10250,
   10378,
   10251,
   10379,
   10385,
   10265,
   10266],
  'annual_from': 3,
  'annual_to': 100,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 282942,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 2415,
   'name': '스터닝',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/2415/zxd9l6h6lxn3idau__1080_790.png',
   'thumb': 'https://static.wanted.co.kr/images/company/2415/zxd9l6h6lxn3idau__400_400.png',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '강남구'},
  'position': '[라우드소싱] 프로덕트 디자이너(UI/UX)',
  'category_tag': {'parent_id': 511, 'id': 594},
  'attraction_tags': [10401,
   10402,
   10468,
   10409,
   10537,
   10413,
   10509,
   10416,
   10417,
   10418,
   10420,
   10399],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10246,
   10247,
   10248,
   10249,
   10377,
   10251,
   10380,
   10253,
   10379,
   10383,
   10384,
   10385,
   10264,
   10266],
  'annual_from': 1,
  'annual_to': 3,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 283435,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 46520,
   'name': '토스인컴',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/46520/jpyhiwrbieuakulq__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/46520/jpyhiwrbieuakulq__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '강남구'},
  'position': 'Frontend Developer',
  'category_tag': {'parent_id': 518, 'id': 939},
  'attraction_tags': [10402,
   10436,
   10407,
   10440,
   10508,
   10511,
   10424,
   10426,
   10398],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10248,
   10377,
   10249,
   10251,
   10379,
   10253,
   10252,
   10384,
   10385,
   10386,
   10264,
   10266],
  'annual_from': 2,
  'annual_to': 10,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 279166,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 63,
   'name': '뱅크샐러드',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/63/bclu6isv9svc7esq__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/63/bclu6isv9svc7esq__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '마포구'},
  'position': '프로덕트 매니저 (Product Manager, PFM)',
  'category_tag': {'parent_id': 507, 'id': 565},
  'attraction_tags': [10508,
   10509,
   10521,
   10523,
   10397,
   10401,
   10403,
   10409,
   10537,
   10412,
   10413,
   10420,
   10423,
   10426,
   10436,
   10439,
   10440,
   10466,
   10468,
   10485,
   10486],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10246,
   10247,
   10248,
   10377,
   10249,
   10250,
   10380,
   10253,
   10378,
   10251,
   10384,
   10385,
   10379,
   10254,
   10382,
   10252,
   10386,
   10383,
   10265,
   10266],
  'annual_from': 0,
  'annual_to': 100,
  'is_newbie': True,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 271805,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 23419,
   'name': '씨제이올리브영(CJ올리브영)',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/23419/f7aifr54bs6x1m9n__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/23419/f7aifr54bs6x1m9n__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '용산구'},
  'position': '신사업 프로덕트 PO',
  'category_tag': {'parent_id': 507, 'id': 565},
  'attraction_tags': [10433,
   10401,
   10468,
   10405,
   10438,
   10564,
   10440,
   10441,
   10408,
   10537,
   10436,
   10486,
   10423,
   10425],
  'skill_tags': [],
  'user_oriented_tags': [10251, 10379, 10253],
  'annual_from': 3,
  'annual_to': 10,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 283738,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 3382,
   'name': '111퍼센트',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/3382/hx3cm8ihl6azoja1__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/3382/hx3cm8ihl6azoja1__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '강남구'},
  'position': '웹 프론트 개발자',
  'category_tag': {'parent_id': 518, 'id': 669},
  'attraction_tags': [10403,
   10436,
   10437,
   10440,
   10408,
   10537,
   10447,
   10418,
   10486,
   10423,
   10398],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10246,
   10247,
   10377,
   10249,
   10251,
   10380,
   10379,
   10253,
   10383,
   10385,
   10265,
   10266],
  'annual_from': 3,
  'annual_to': 100,
  'is_newbie': False,
  'reward': {'id': None,
   'wd_id': None,
   'country': 'kr',
   'user_country': 'KR',
   'reward_recommender': 500000,
   'reward_recommendee': 500000,
   'reward_recommender_unit': 'KRW',
   'reward_recommendee_unit': 'KRW',
   'formatted_total': '100만원',
   'formatted_recommender': '50만원',
   'formatted_recommendee': '50만원'},
  'employment_type': 'regular',
  'additional_apply_type': None},
 {'id': 282831,
  'reward_total': '100만원',
  'is_bookmark': False,
  'company': {'id': 2221,
   'name': '넷마블',
   'application_response_stats': {'avg_rate': 0.0, 'level': 'very_low'}},
  'title_img': {'origin': 'https://static.wanted.co.kr/images/company/2221/wxinzjfpwfkplncw__1080_790.jpg',
   'thumb': 'https://static.wanted.co.kr/images/company/2221/wxinzjfpwfkplncw__400_400.jpg',
   'video': None},
  'address': {'country': '한국', 'location': '서울', 'district': '구로구'},
  'position': '웹 백엔드 개발자',
  'category_tag': {'parent_id': 518, 'id': 873},
  'attraction_tags': [10467,
   10404,
   10437,
   10564,
   10468,
   10440,
   10409,
   10413,
   10509,
   10447,
   10485,
   10422,
   10486,
   10425,
   10427,
   10396],
  'skill_tags': [],
  'user_oriented_tags': [10245,
   10377,

In [4]:
ids = get_ids(posts)
ids

[283170,
 282132,
 282809,
 278301,
 279483,
 282658,
 282656,
 280236,
 282846,
 282942,
 283435,
 279166,
 271805,
 283738,
 282831,
 227561,
 281356,
 278837,
 277111,
 280245,
 283875,
 284592,
 279823,
 284097,
 286101,
 275991,
 282533,
 279453,
 280404,
 276130,
 281333,
 281384,
 281477,
 285212,
 278604,
 286509,
 202035,
 262948,
 281396,
 282961,
 251744,
 283146,
 285600,
 281191,
 273518,
 279842,
 280688,
 282556,
 189899,
 283312,
 271204,
 283216,
 279405,
 280758,
 282836,
 271186,
 283821,
 282770,
 270533,
 280138,
 282655,
 284431,
 280517,
 278651,
 271143,
 284064,
 283438,
 284928,
 276991,
 48832,
 282178,
 284557,
 222071,
 283229,
 285788,
 283599,
 232743,
 284161,
 286440,
 286443,
 249296,
 279221,
 284772,
 283040,
 226948,
 274123,
 282137,
 275348,
 286441,
 284087,
 194059,
 279162,
 278634,
 283348,
 282256,
 285838,
 278425,
 244778,
 273278,
 277505,
 283060,
 227480,
 168297,
 283217,
 282782,
 263714,
 275967,
 244761,
 178777,
 259053,
 279062,
 280571,
 254014,
 260703,
 281404,
 254015,
 281605,
 261137,
 235950,
 274822,
 283235,
 274184,
 286433,
 283468,
 285036,
 281358,
 284102,
 283846,
 284788,
 281824,
 171712,
 281418,
 95385,
 283155,
 286404,
 260415,
 268127,
 236476,
 281379,
 273728,
 286471,
 217852,
 281945,
 284114,
 284243,
 152424,
 267690,
 216360,
 284077,
 202034,
 284711,
 268957,
 281433,
 283258,
 286360,
 282559,
 284068,
 283086,
 282309,
 278677,
 279411,
 279400,
 276263,
 110433,
 280612,
 286806,
 262596,
 285996,
 283747,
 259396,
 202672,
 277582,
 274200,
 282597,
 286462,
 283033,
 283646,
 281355,
 281893,
 280199,
 246260,
 279935,
 286158,
 284100,
 130436,
 283240,
 278626,
 243835,
 284410,
 282364,
 281460,
 281052,
 259187,
 284741,
 261153,
 280084,
 283586,
 189909,
 281366,
 277836,
 279975,
 274888,
 282948,
 139067,
 284856,
 276235,
 276764,
 263613,
 279303,
 282532,
 284916,
 282729,
 280502,
 277153,
 245367,
 177802,
 192389,
 284028,
 283954,
 217834,
 286553,
 258521,
 285382,
 285035,
 213554,
 284083,
 284019,
 283332,
 281506,
 264022,
 256259,
 260465,
 281357,
 279808,
 283918,
 280492,
 279638,
 285489,
 284290,
 222550,
 179426,
 276884,
 281464,
 279145,
 174830,
 279805,
 286988,
 283323,
 283516,
 284807,
 283081,
 282654,
 282565,
 185388,
 283722,
 283626,
 257699,
 278524,
 284408,
 283399,
 202200,
 280904,
 282278,
 275940,
 277031,
 207573,
 252207,
 86060,
 284888,
 286005,
 283973,
 283053,
 283158,
 261894,
 280489,
 281757,
 278348,
 231568,
 275771,
 277639,
 265906,
 282981,
 272766,
 274256,
 270367,
 283585,
 285733,
 259112,
 282907,
 281110,
 278793,
 281278,
 277309,
 276168,
 275176,
 44837,
 286506,
 285966,
 281468,
 262250,
 282502,
 247023,
 270013,
 255280,
 252404,
 281866,
 283597,
 281867,
 281387,
 270067,
 223783,
 285594,
 278408,
 281365,
 247595,
 279563,
 284443,
 115547,
 282994,
 282573,
 281306,
 281271,
 277578,
 274496,
 181466,
 263386,
 284265,
 284092,
 282868,
 282837,
 282718,
 281912,
 118971,
 282125,
 283740,
 248679,
 282841,
 282750,
 182385,
 281342,
 242469,
 268174,
 276062,
 264057,
 281504,
 287027,
 286457,
 283871,
 282369,
 285067,
 283408,
 282940,
 280550,
 280196,
 262346,
 271142,
 282165,
 197921,
 252001,
 283910,
 268137,
 95481,
 282466,
 281994,
 280829,
 276982,
 279191,
 262802,
 264056,
 254414,
 209695,
 284809,
 279948,
 259159,
 286150,
 284110,
 283624,
 284306,
 282871,
 283320,
 283574,
 198382,
 262418,
 233010,
 281309,
 273799,
 276047,
 278593,
 277167,
 272199,
 283584,
 283400,
 280666,
 280669,
 283857,
 283250,
 284895,
 284079,
 283872,
 272350,
 282521,
 282246,
 279695,
 248771,
 281108,
 276453,
 260018,
 238235,
 82139,
 257306,
 254545,
 238237,
 286407,
 286438,
 282251,
 259509,
 284266,
 257692,
 280602,
 284183,
 249018,
 270114,
 282797,
 234830,
 280960,
 257207,
 278705,
 276525,
 268260,
 168206,
 280524,
 280711,
 283858,
 285542,
 283193,
 285980,
 285869,
 282280,
 89896,
 284436,
 278271,
 282017,
 284319,
 190225,
 282628,
 284301,
 284259,
 284115,
 283502,
 281416,
 283038,
 259032,
 281610,
 281398,
 281395,
 281045,
 273028,
 278290,
 276363,
 281568,
 284899,
 280701,
 284581,
 284022,
 284120,
 284096,
 282579,
 281859,
 281407,
 281343,
 238294,
 280137,
 279515,
 275817,
 269975,
 273991,
 269006,
 125138,
 264364,
 283219,
 173289,
 283750,
 283160,
 283093,
 126670,
 281217,
 279187,
 271352,
 268725,
 238949,
 865,
 286296,
 286435,
 283863,
 286140,
 278472,
 213717,
 285341,
 284914,
 278881,
 282762,
 282732,
 282501,
 281977,
 279559,
 75323,
 247869,
 278277,
 230044,
 272947,
 282235,
 279434,
 284660,
 218967,
 196778,
 283748,
 279843,
 284910,
 283035,
 283889,
 283407,
 234501,
 279873,
 279042,
 276118,
 247240,
 866,
 206124,
 285628,
 270765,
 212202,
 286142,
 270110,
 284105,
 284082,
 270159,
 130434,
 283372,
 283351,
 283078,
 283007,
 281273,
 257821,
 223157,
 276746,
 119455,
 279385,
 247032,
 273011,
 262671,
 253017,
 282962,
 282900,
 281791,
 229817,
 254693,
 284536,
 285113,
 284915,
 281402,
 262317,
 284579,
 284510,
 284030,
 266969,
 283861,
 282800,
 282527,
 281222,
 281482,
 277219,
 263167,
 272953,
 271443,
 283083,
 275855,
 286812,
 281116,
 280077,
 284824,
 279829,
 280621,
 281767,
 284093,
 283172,
 254630,
 274293,
 281491,
 281326,
 277224,
 278328,
 141545,
 272927,
 272151,
 281964,
 286442,
 275683,
 286143,
 239276,
 285668,
 284104,
 280232,
 284599,
 284370,
 284350,
 250715,
 282996,
 283546,
 273555,
 282859,
 281307,
 281642,
 251377,
 281548,
 237445,
 279551,
 279060,
 278082,
 275641,
 220057,
 273420,
 225379,
 246286,
 286373,
 278733,
 266532,
 285857,
 280030,
 285020,
 227263,
 284505,
 284371,
 284073,
 284119,
 283947,
 283758,
 281423,
 159753,
 283057,
 276939,
 282936,
 282914,
 282583,
 281792,
 253089,
 280929,
 279635,
 278860,
 276993,
 270763,
 265214,
 235952,
 265111,
 264624,
 193258,
 245979,
 283685,
 282734,
 281453,
 286460,
 278155,
 271696,
 285791,
 285727,
 216301,
 284518,
 216514,
 284544,
 284157,
 272687,
 283137,
 282749,
 282725,
 279130,
 261317,
 281552,
 254902,
 280990,
 278739,
 257214,
 269359,
 280523,
 286919,
 279340,
 286402,
 286434,
 286436,
 286243,
 285655,
 285464,
 284164,
 282356,
 284501,
 197759,
 284177,
 262772,
 283953,
 267405,
 283019,
 283346,
 281473,
 282944,
 65132,
 280514,
 281649,
 281437,
 256339,
 279528,
 225171,
 252123,
 282889,
 243652,
 284369,
 285647,
 102917,
 285468,
 189895,
 285291,
 282884,
 284931,
 284795,
 282236,
 245557,
 283064,
 283031,
 283002,
 282277,
 282267,
 281687,
 278536,
 281996,
 281756,
 280779,
 281319,
 272283,
 56331,
 278427,
 278302,
 275774,
 264538,
 261188,
 283263,
 278861,
 286219,
 286229,
 286111,
 286020,
 285795,
 283835,
 285079,
 285475,
 284929,
 214484,
 284364,
 284090,
 271310,
 283581,
 236190,
 282799,
 280379,
 139409,
 282059,
 280891,
 281894,
 263493,
 162405,
 281279,
 281072,
 280460,
 279651,
 279919,
 279530,
 272767,
 278907,
 278722,
 275864,
 275491,
 209728,
 142950,
 254695,
 207345,
 271967,
 286388,
 149552,
 126972,
 259157,
 265428,
 277935,
 285526,
 194945,
 278410,
 284406,
 284639,
 284555,
 283730,
 276968,
 283371,
 257130,
 282788,
 166462,
 282365,
 282342,
 282172,
 281556,
 281595,
 276619,
 269549,
 279724,
 279689,
 278135,
 273818,
 269717,
 257253,
 263095,
 281485,
 275453,
 249574,
 283746,
 286207,
 259391,
 283984,
 266886,
 88904,
 285681,
 264990,
 263476,
 285461,
 282919,
 264618,
 284376,
 283494,
 284166,
 284094,
 250763,
 283764,
 283215,
 283715,
 283675,
 282112,
 282980,
 273281,
 283308,
 283175,
 282635,
 281081,
 281439,
 180676,
 280260,
 279781,
 273825,
 272997,
 278013,
 272456,
 271349,
 260746,
 247066,
 284466,
 283735,
 281296,
 281392,
 269023,
 279210,
 251865,
 284006,
 282347,
 284422,
 218327,
 284700,
 284528,
 284402,
 283880,
 262119,
 282796,
 283525,
 280609,
 283047,
 275086,
 282895,
 282358,
 278122,
 282272,
 281935,
 275694,
 279617,
 281409,
 281400,
 262773,
 280947,
 269641,
 280343,
 191444,
 279918,
 279905,
 269150,
 206658,
 277728,
 277330,
 276294,
 275995,
 253400,
 260009,
 266984,
 262790,
 231006,
 285882,
 282581,
 286747,
 282086,
 30767,
 283434,
 285884,
 262627,
 278097,
 145274,
 280928,
 276836,
 254243,
 284452,
 284112,
 278451,
 279700,
 283806,
 283804,
 283639,
 257235,
 264404,
 282712,
 282699,
 276689,
 280495,
 280501,
 253179,
 282133,
 278533,
 278165,
 279610,
 279562,
 279200,
 278168,
 274961,
 272839,
 266141,
 267761,
 254411,
 11112,
 273980,
 283838,
 283647,
 286500,
 260453,
 253092,
 251042,
 284662,
 280156,
 285808,
 285635,
 243156,
 280887,
 284734,
 284601,
 284227,
 284111,
 279120,
 283749,
 283710,
 283654,
 274889,
 283319,
 283008,
 283165,
 252976,
 115964,
 282299,
 281885,
 273598,
 279133,
 259384,
 275993,
 277928,
 280652,
 272333,
 277130,
 191441,
 279910,
 255944,
 277700,
 267519,
 209886,
 259598,
 238086,
 264054,
 258479,
 253531,
 205931,
 284317,
 285098,
 286192,
 286380,
 285573,
 180371,
 ...]

In [5]:
post_detail = get_wanted_detail_crawling(ids)

Fetching Detail Contents:  93%|█████████▎| 9167/9846 [38:51<02:58,  3.80post/s]  WARNING:root:jid=286932 HTTPSConnectionPool(host='www.wanted.co.kr', port=443): Read timed out. (read timeout=10) → retry in 1.7s
Fetching Detail Contents: 100%|██████████| 9846/9846 [42:07<00:00,  3.90post/s]

In [8]:
post_detail

,position,intro,main_tasks,requirements,preferred_points,benefits,hire_rounds,attraction,company,country,location,district,category_parent,category_child,skill,annual_from,annual_to,is_newbie,due_time,job_id
0,프로모션 ​기획 ​마케터,컬리 온사이트 ​마케팅 조직은 고객이 컬리에서 ​즐거운 ​장보기 경험을 ​하도록 돕...,사업 목표 달성을 위한 온사이트 프로모션 전략 수립 및 실행\n\n1) 연/분기/월...,[경험]\n• 최소 1년 이상의 유관 경험 또는 그에 준하는 역량을 보유하신 분\n...,"• Amplitude 활용이 가능하신 분\n• 서비스 마케팅, 사업 전략까지 확장 ...","모두가 집중하고 성장할 수 있도록, 최적의 근무 환경을 제공해요\n \n• 리프레시...",[합류 여정]\n지원서 제출 ＞직무 적합성 인터뷰 ＞ 직무적합성검사 및 종합 인터뷰...,"[의료비지원, 휴가비, 유급휴가, 커피·스낵바, 1,001~10,000명, 설립10...",컬리,한국,서울,강남구,마케팅·광고,"[마케터, 디지털 마케터, 모바일마케팅]",[],3,10,False,None,283170
1,콘텐츠 에디터,구분 : 신입/경력\n계약기간: 12개월\n\n[조직소개]\n콘텐츠기획팀은 크리에이...,콘텐츠기획팀은 단순히 ‘글을 잘 쓰는 사람’을 찾지 않습니다.\n사용자가 무엇을 클...,"• 콘텐츠 운영의 흐름을 이해하고, 반복적인 업무에도 책임감 있게 임할 수 있는 분...","• 식품, 음식, 라이프스타일 관련 콘텐츠나 트렌드에 관심이 많은 분\n• 온라인 ...",[우아한혜택 미리보기]\n- 일한 만큼 드립니다. 매월 소정근로시간 초과 시 분 단...,,"[복지포인트, 보너스, 단체보험, 어린이돌봄, 장비지원, 커피·스낵바, 대출지원, ...",우아한형제들(배달의민족),한국,서울,송파구,마케팅·광고,"[카피라이터, 콘텐츠 마케터]",[],0,100,True,None,282132
2,프로덕트 디자이너(PD),“모든 사람이 편안하고 안전하게 이동할 수 있는 것”\n\n타다가 모빌리티 시장의 ...,VCNC의 프로덕트 디자이너(PD)는 제품 기획/개발 과정에서 핵심적인 역할을 담당...,• 최소 3년 이상의 프로덕트 디자이너 경력이 있는 분\n• 심미적이고 깔끔한 GU...,• 모빌리티 업계나 스타트업 산업에 대한 높은 이해도를 가지고 계신 분\n• 디자인...,# 몰입을 위한 모든 것을 지원하는 타다 BOOST PACK \n\n[ Flexib...,[채용 Process]\n• 서류 전형 - 직무 인터뷰 - 컬쳐핏 인터뷰 - 연봉 ...,"[건강검진지원, 커피·스낵바, 자기계발지원, 식대지원, 연봉상위6~10%, 설립10...",타다(VCNC),한국,서울,성동구,디자인,"[모바일 디자이너, UI,GUI 디자이너, UX 디자이너]",[],3,7,False,None,282809
3,UIUX 디자이너(신사업 프로덕트),"All Live Better,\n\nNo.1 헬스&뷰티 스토어 올리브영은 20년 이...","• 올리브영 신사업 디플롯 프로덕트 웹/APP 디자인\n• UI디자인, UX설계 및...",* 포트폴리오 필수 제출 바랍니다.\n• 포트폴리오 파일 혹은 포트폴리오 사이트 U...,[Skill/Experience]\n• 이커머스 플랫폼 프로젝트 경험\n• Agil...,• CJ그룹 계열사 인프라 40% 할인\n• 카페테리아 포인트(현금성 복지 포인트)...,※ 전형 안내\n\n서류전형 - 1차면접 - 온라인 인성검사 - 2차면접 - Ref...,"[휴가비, 의료비지원, 건강검진지원, 편의시설, 자기계발지원, 수평적조직, 설립4~...",씨제이올리브영(CJ올리브영),한국,서울,용산구,디자인,[UX 디자이너],[],4,11,False,None,278301
4,Frontend Developer,[꼭 확인해 주세요]\n•이력서 및 제출 서류에 허위 사실이 발견되거나 근무 이력 ...,[지금까진 이런 일을 했어요]\n•누구나 쉽게 원하는 결제 경험을 만들 수 있도록 ...,[이런 분과 함께하고 싶어요]\n•개발자 경험에 대해 높은 가치를 두고 있는 분\n...,"[이런 경험이 있다면 이력서에 꼭 작성해 주세요]\n•TypeScript, Flow...",[이렇게 일해요]\n• 자율과 책임의 문화: 토스는 Manager가 아닌 Maker...,[토스페이먼츠로의 합류 여정]\n•서류접수 ＞ 사전 과제 ＞ 직무 인터뷰 ＞ 문화적...,"[단체보험, 편의시설, 보너스, 커피·스낵바, 설립4~9년, 유급휴가, 301~1,...",토스페이먼츠,한국,서울,강남구,개발,[프론트엔드 개발자],[],0,100,True,2025-06-30,279483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9841,통합인허가 팀장,엔코아네트웍스 통합인허가 팀장 채용합니다.,"• 통합인허가, 메체법 인허가, 엔지니어링 등 업무 수행\n• 전형 절차 : 서류전...","• 통합인허가 수행실적 2건이상 - 실무PM수행(석유화학, 비철, 철강)\n• 공정...",• 매체법 인허가 경력우대\n• 연령 : 제한없음(30~40대 우대)\n• 입사시기...,• 명절 상여금/하계휴가지원비/연말 성과금 지급\n• 직급수당/직무수당/자격수당/잔...,None,"[식대지원, 커피·스낵바, 보너스, 50명이하, 인원 급성장, 설립10년이상, 연봉...",엔코아네트웍스,한국,울산,남구,엔지니어링·설계,"[환경 엔지니어, 환경 안전기사]",[],5,15,False,None,124655
9842,친환경 올인원 에어케어시스템 PCB 및 펌웨어,안녕하세요. 엔트 입니다.\n당사는 탄소저감 공조시스템 개발을 통해 ESG 기업으로...,"• 전자제품, 공조기 PCB 개발 및 외주업체 관리\n• 전자제품, 공조기 펌웨어 ...","• 관련경험 5년 이상\n• 해외여행에 결격사유가 없는 분\n• 전기, 자동제어 개...",• 인버터 압축기 경험\n• 에어컨 개발 경험,• 중식제공\n• 카페테리아\n• 4대보험\n• 연차휴가\n• 주 5일근무\n• 경...,None,"[편의시설, 식대지원, 50명이하, 설립10년이상, 연봉상위11~20%]",엔트,한국,경기,부천시,개발,"[임베디드 개발자, 하드웨어 엔지니어, 소프트웨어 엔지니어]",[],5,10,False,None,76159
9843,"PCB약품 개발, 제조업, 화학약품","NR지엔씨는 PCB 반도체 , 인쇄회로기판, 디스플레이 관련 약품 개발을 통해\n기...","• 반도체, 인쇄회로기판, 디스플레이 관련 약품 개발\n• 신규약품 개발 및 분석\...",• 화학관련학과 박사 졸업,• 개별 성과에 따른 인센티브 지급\n• 개인 차량 제공 (차량 관련 모든 유지비용...,• 연봉 외 개별 인센티브 지급\n• 식사제공 (식사 or 식대 지급)\n• 통신비...,None,"[식대지원, 보너스, 설립10년이상, 통신비]",엔알지엔씨,한국,경기,수원시,개발,[기술지원],[],0,1,True,None,87790
9844,C/C++개발자(3년~),"당사는 X-ray 제조社로서 코스닥 상장, 매출액 650억 / 인원 240명 글로벌...",• SW 영상기기 개발\n• SW 영상 뷰어\n• SW 3D,"• C++ 개발 가능자\n• C++ / QT 개발가능자, OpenGL(VTK) 개...","• PACS 개발경험자, Agile Process, XP, Scrum, Pari...",• 2년에 1번 대명리조트 콘도/호텔 이용료 전액 지급\n• 듀얼 모니터 지급\n•...,None,"[보너스, 연봉상위11~20%, 301~1,000명, 인원 급성장, 설립10년이상,...",제노레이,한국,경기,성남시,개발,"[파이썬 개발자, C,C++ 개발자, 소프트웨어 엔지니어]",[],3,10,False,None,80732
9845,퍼포먼스 마케터,"지엔터프라이즈는 중소 비즈니스가 더 높은 차원의 목표를 이루도록, 까다로운 세무 및...",• 비즈니스의 중장기적인 성장을 함께 고려하여 디지털 광고 캠페인을 운영합니다\n•...,• 퍼포먼스 마케팅 혹은 유사 직무 관련 경험이 5년 이상인 분\n• 예산 계획에 ...,• IT 서비스 ㆍ스타트업 혹은 빠르게 성장하는 환경에서 업무 경험이 있으신 분...,[행복하게 일할 수 있도록] \n• 오전 8~11시 자율 출근\n• 3년 근속 14...,서류전형 - 1차 직무인터뷰 - 2차 컬쳐핏 인터뷰 - 처우협의 - 입사,"[건강검진지원, 커피·스낵바, 51~300명, 설립4~9년, 인원 급성장, 연봉상위...",지엔터프라이즈,한국,서울,강남구,마케팅·광고,[퍼포먼스 마케터],[],4,10,False,None,287123

In [7]:
post_detail.to_json('../Data_Files/wanted_detail_20250515.txt', force_ascii=False)

OSError: Cannot save file into a non-existent directory: '../Data_Files'

In [9]:
post_improve_detail = toImproveDataFrame(post_detail)

In [10]:
split_columns = ['main_tasks', 'requirements', 'preferred_points', 'benefits', 'hire_rounds']

for column in split_columns:
    post_improve_detail[column] = post_improve_detail[column].apply(
        lambda x: x.split('\n') if isinstance(x, str) else x)

post_improve_detail.drop(columns=['country'], inplace=True)

In [11]:
post_improve_detail.drop_duplicates(subset=['position'], inplace=True)

In [12]:
post_improve_detail.set_index('job_id', inplace=True)

In [13]:
columns = post_improve_detail.columns
columns = columns.tolist()
for col in columns:
    post_improve_detail[col] = post_improve_detail[col].apply(
        lambda x: x.replace('\n', '') if isinstance(x, str) else x)

In [14]:
post_improve_detail.rename(columns={
    'position': '제목',
    'intro': '회사 소개',
    'main_tasks': '주요 업무',
    'requirements': '자격 요건',
    'preferred_points': '우대 사항',
    'benefits': '복지',
    'hire_rounds': '채용절차',
    'attraction': '장점',
    'company': '회사명',
    'location': '근무지',
    'district': '지역',
    'category_parent': '직군',
    'category_child': '직무',
    'skill': '기술 스택',
    'annual_from': '요구 최소 경력',
    'annual_to': '요구 최대 경력',
    'is_newbie': '신입 지원 가능 여부',
    'due_time': '마감일',
}, inplace=True)

In [15]:
import numpy as np

# 공백·탭·개행 모두 제거한 뒤 '' 이면 상시 공고
post_improve_detail["마감일"] = np.where(
    post_improve_detail["마감일"].astype(str).str.strip() == "",
    "상시 공고",
    post_improve_detail["마감일"]
)

In [16]:
post_improve_detail

,제목,회사 소개,주요 업무,자격 요건,우대 사항,복지,채용절차,장점,회사명,근무지,지역,직군,직무,기술 스택,요구 최소 경력,요구 최대 경력,신입 지원 가능 여부,마감일
job_id,,,,,,,,,,,,,,,,,,
283170,프로모션 기획 마케터,컬리 온사이트 마케팅 조직은 고객이 컬리에서 즐거운 장보기 경험을 하도록 돕고 그에...,"[사업 목표 달성을 위한 온사이트 프로모션 전략 수립 및 실행, , 1 연분기월 별...","[경험, 최소 1년 이상의 유관 경험 또는 그에 준하는 역량을 보유하신 분, 경...","[Amplitude 활용이 가능하신 분, 서비스 마케팅, 사업 전략까지 확장 가능...","[모두가 집중하고 성장할 수 있도록, 최적의 근무 환경을 제공해요, , 리프레시...","[합류 여정, 지원서 제출 직무 적합성 인터뷰 직무적합성검사 및 종합 인터뷰 최...","[의료비지원, 휴가비, 유급휴가, 커피스낵바, 1,00110,000명, 설립10년이...",컬리,서울,강남구,마케팅광고,"[마케터, 디지털 마케터, 모바일마케팅]",[],3,10,False,상시 공고
282132,콘텐츠 에디터,구분 신입경력계약기간 12개월조직소개콘텐츠기획팀은 크리에이티브 부문 콘텐츠크리에이...,"[콘텐츠기획팀은 단순히 글을 잘 쓰는 사람을 찾지 않습니다, 사용자가 무엇을 클릭하...","[콘텐츠 운영의 흐름을 이해하고, 반복적인 업무에도 책임감 있게 임할 수 있는 분,...","[식품, 음식, 라이프스타일 관련 콘텐츠나 트렌드에 관심이 많은 분, 온라인 커머...","[우아한혜택 미리보기, 일한 만큼 드립니다 매월 소정근로시간 초과 시 분 단위로 ...",[],"[복지포인트, 보너스, 단체보험, 어린이돌봄, 장비지원, 커피스낵바, 대출지원, 연...",우아한형제들배달의민족,서울,송파구,마케팅광고,"[카피라이터, 콘텐츠 마케터]",[],0,100,True,상시 공고
282809,프로덕트 디자이너PD,모든 사람이 편안하고 안전하게 이동할 수 있는 것타다가 모빌리티 시장의 이용자들에게...,[VCNC의 프로덕트 디자이너PD는 제품 기획개발 과정에서 핵심적인 역할을 담당하며...,"[최소 3년 이상의 프로덕트 디자이너 경력이 있는 분, 심미적이고 깔끔한 GUI를...","[모빌리티 업계나 스타트업 산업에 대한 높은 이해도를 가지고 계신 분, 디자인 시...","[# 몰입을 위한 모든 것을 지원하는 타다 BOOST PACK , , Flexib...","[채용 Process, 서류 전형 직무 인터뷰 컬쳐핏 인터뷰 연봉 및 처우 ...","[건강검진지원, 커피스낵바, 자기계발지원, 식대지원, 연봉상위610, 설립10년이상...",타다VCNC,서울,성동구,디자인,"[모바일 디자이너, UI,GUI 디자이너, UX 디자이너]",[],3,7,False,상시 공고
278301,UIUX 디자이너신사업 프로덕트,"All Live Better,No1 헬스뷰티 스토어 올리브영은 20년 이상 축적된 ...","[올리브영 신사업 디플롯 프로덕트 웹APP 디자인, UI디자인, UX설계 및 디자...","[포트폴리오 필수 제출 바랍니다, 포트폴리오 파일 혹은 포트폴리오 사이트 URL과...","[SkillExperience, 이커머스 플랫폼 프로젝트 경험, Agile 업무...","[CJ그룹 계열사 인프라 40 할인, 카페테리아 포인트현금성 복지 포인트혜택 개인...","[전형 안내, , 서류전형 1차면접 온라인 인성검사 2차면접 Referenc...","[휴가비, 의료비지원, 건강검진지원, 편의시설, 자기계발지원, 수평적조직, 설립49...",씨제이올리브영CJ올리브영,서울,용산구,디자인,[UX 디자이너],[],4,11,False,상시 공고
279483,Frontend Developer,꼭 확인해 주세요이력서 및 제출 서류에 허위 사실이 발견되거나 근무 이력 중 징계사...,"[지금까진 이런 일을 했어요, 누구나 쉽게 원하는 결제 경험을 만들 수 있도록 치열...","[이런 분과 함께하고 싶어요, 개발자 경험에 대해 높은 가치를 두고 있는 분, 자동...","[이런 경험이 있다면 이력서에 꼭 작성해 주세요, TypeScript, Flow를 ...","[이렇게 일해요, 자율과 책임의 문화 토스는 Manager가 아닌 Maker들로 ...","[토스페이먼츠로의 합류 여정, 서류접수 사전 과제 직무 인터뷰 문화적합성 인터...","[단체보험, 편의시설, 보너스, 커피스낵바, 설립49년, 유급휴가, 3011,000...",토스페이먼츠,서울,강남구,개발,[프론트엔드 개발자],[],0,100,True,20250630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125154,통합인허가 임원,엔코아네트웍스 통합인허가 임원 채용합니다,"[통합인허가, 매채법 인허가, 엔지니어링 등 업무 수행, 전형절차 서류전형 1...","[통합인허가 수행실적 2건이상 실무PM수행석유화학, 비철, 철강, 공정 해석분석...","[매체법 인허가 경력우대, 연령 제한없음3040대 우대, 입사시기 9월즉시 ...","[명절 상여금하계휴가지원비연말 성과금 지급, 직급수당직무수당자격수당잔여연차수당OT...",[],"[식대지원, 커피스낵바, 보너스, 50명이하, 인원 급성장, 설립10년이상, 연봉 ...",엔코아네트웍스,울산,남구,엔지니어링설계,"[환경 엔지니어, 환경 안전기사]",[],5,15,False,상시 공고
124655,통합인허가 팀장,엔코아네트웍스 통합인허가 팀장 채용합니다,"[통합인허가, 메체법 인허가, 엔지니어링 등 업무 수행, 전형 절차 서류전형 ...","[통합인허가 수행실적 2건이상 실무PM수행석유화학, 비철, 철강, 공정 해석분석...","[매체법 인허가 경력우대, 연령 제한없음3040대 우대, 입사시기 9월즉시 ...","[명절 상여금하계휴가지원비연말 성과금 지급, 직급수당직무수당자격수당잔여연차수당OT...",[],"[식대지원, 커피스낵바, 보너스, 50명이하, 인원 급성장, 설립10년이상, 연봉 ...",엔코아네트웍스,울산,남구,엔지니어링설계,"[환경 엔지니어, 환경 안전기사]",[],5,15,False,상시 공고
76159,친환경 올인원 에어케어시스템 PCB 및 펌웨어,안녕하세요 엔트 입니다당사는 탄소저감 공조시스템 개발을 통해 ESG 기업으로 성장하...,"[전자제품, 공조기 PCB 개발 및 외주업체 관리, 전자제품, 공조기 펌웨어 개발...","[관련경험 5년 이상, 해외여행에 결격사유가 없는 분, 전기, 자동제어 개발업무...","[인버터 압축기 경험, 에어컨 개발 경험]","[중식제공, 카페테리아, 4대보험, 연차휴가, 주 5일근무, 경조사 지원,...",[],"[편의시설, 식대지원, 50명이하, 설립10년이상, 연봉상위1120]",엔트,경기,부천시,개발,"[임베디드 개발자, 하드웨어 엔지니어, 소프트웨어 엔지니어]",[],5,10,False,상시 공고
87790,"PCB약품 개발, 제조업, 화학약품","NR지엔씨는 PCB 반도체 , 인쇄회로기판, 디스플레이 관련 약품 개발을 통해기술가...","[반도체, 인쇄회로기판, 디스플레이 관련 약품 개발, 신규약품 개발 및 분석, ...",[화학관련학과 박사 졸업],"[개별 성과에 따른 인센티브 지급, 개인 차량 제공 차량 관련 모든 유지비용 지급...","[연봉 외 개별 인센티브 지급, 식사제공 식사 or 식대 지급, 통신비 지원, ...",[],"[식대지원, 보너스, 설립10년이상, 통신비]",엔알지엔씨,경기,수원시,개발,[기술지원],[],0,1,True,상시 공고
80732,CC++개발자3년,"당사는 Xray 제조로서 코스닥 상장, 매출액 650억 인원 240명 글로벌 기업...","[SW 영상기기 개발, SW 영상 뷰어, SW 3D]","[C++ 개발 가능자, C++ QT 개발가능자, OpenGLVTK 개발가능자,...","[PACS 개발경험자, Agile Process, XP, Scrum, Pari,...","[2년에 1번 대명리조트 콘도호텔 이용료 전액 지급, 듀얼 모니터 지급, 통근버...",[],"[보너스, 연봉상위1120, 3011,000명, 인원 급성장, 설립10년이상, 자기...",제노레이,경기,성남시,개발,"[파이썬 개발자, C,C++ 개발자, 소프트웨어 엔지니어]",[],3,10,False,상시 공고

In [17]:
#post_improve_detail.T.to_json('../../Data_Files/wanted_detail_improve_20250515.txt', force_ascii=False)
post_improve_detail.T.to_json('../../Data_Files/wanted_detail_improve_20250604.json', force_ascii=False)

In [4]:
with open('../../Data_Files/wanted_detail_improve_20250515.txt', 'r', encoding='utf-8') as f:
    post_improve_detail = json.load(f)

AttributeError: 'dict' object has no attribute 'to_json'

In [6]:
with open('../../wanted_detail_improve_20250604.json', 'w', encoding='utf-8') as f:
    json.dump(post_improve_detail, f, ensure_ascii=False, indent=4)